server:
  port: 8888


spring:
  config:
    import: classpath:security-rbac.yml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7777/realms/ecommerce-realm
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:9080
          predicates:
            - Path=/api/v1/products/**
          filters:
            - RewritePath=/product-service/(?<remaining>.*), /product-service/${remaining}
        - id: authentication-service
          uri: http://localhost:9081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/authentication-service/(?<remaining>.*), /authentication-service/${remaining}
  application:
    name: gateway-server



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

